name = "selarasinvite-backend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[[vars]]
DATABASE_URL="postgresql://postgres.ibekxcvncqwwamfsrrgb:A6u5I5NeXsaas@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
SUPABASE_URL="https://ibekxcvncqwwamfsrrgb.supabase.co"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliZWt4Y3ZuY3F3d2FtZnNycmdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODU3NzcsImV4cCI6MjA3MzE2MTc3N30.-v7OSZzHJH8XgQA-2qA2d_aKDoDcVKWI1St48Di5Pls"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }