export const schemas = {
  User: {
    type: "object",
    properties: {
      id: { type: "string", format: "uuid" },
      name: { type: "string" },
      email: { type: "string", format: "email" },
      emailVerified: { type: "string", format: "date-time" },
      image: { type: "string" },
      role: { $ref: "#/components/schemas/Role" },
      address: { type: "string" },
      phone: { type: "string" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  CreateUserRequest: {
    type: "object",
    required: ["email", "password"],
    properties: {
      name: { type: "string" },
      email: { type: "string", format: "email" },
      password: { type: "string", format: "password" },
      confirmPassword: { type: "string", format: "password" },
    },
  },
  LoginRequest: {
    type: "object",
    required: ["email", "password"],
    properties: {
      email: { type: "string", format: "email" },
      password: { type: "string", format: "password" },
    },
  },
  LoginResponse: {
    type: "object",
    properties: {
      accessToken: { type: "string" },
      refreshToken: { type: "string" },
    },
  },
  UpdateUserRequest: {
    type: "object",
    properties: {
      name: { type: "string" },
      email: { type: "string", format: "email" },
      address: { type: "string" },
      phone: { type: "string" },
    },
  },
  Catalog: {
    type: "object",
    properties: {
      id: { type: "string", format: "uuid" },
      name: { type: "string" },
      description: { type: "string" },
      content: { type: "string" },
      image: { type: "string" },
      price: { type: "integer" },
      withPhoto: { type: "boolean" },
      hexCode: { type: "string" },
      slug: { type: "string" },
      isPublish: { type: "boolean" },
      sectionType: {
        type: "array",
        items: { $ref: "#/components/schemas/SectionType" },
      },
      categoryId: { type: "string", format: "uuid" },
      userId: { type: "string", format: "uuid" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  CreateCatalogRequest: {
    type: "object",
    required: ["name", "description", "price"],
    properties: {
      name: { type: "string" },
      description: { type: "string" },
      content: { type: "string" },
      image: { type: "string" },
      price: { type: "integer" },
      withPhoto: { type: "boolean" },
      hexCode: { type: "string" },
      sectionType: {
        type: "array",
        items: { $ref: "#/components/schemas/SectionType" },
      },
      categoryId: { type: "string", format: "uuid" },
    },
  },
  Invitation: {
    type: "object",
    properties: {
      id: { type: "string", format: "uuid" },
      title: { type: "string" },
      slug: { type: "string" },
      userId: { type: "string", format: "uuid" },
      catalogId: { type: "string", format: "uuid" },
      isCreating: { type: "string" },
      tagsTheme: { type: "string" },
      note: { type: "string" },
      isActive: { type: "boolean" },
      transactionId: { type: "string", format: "uuid" },
      reservationId: { type: "string", format: "uuid" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  CreateInvitationRequest: {
    type: "object",
    required: ["title", "catalogId"],
    properties: {
      title: { type: "string" },
      catalogId: { type: "string", format: "uuid" },
      tagsTheme: { type: "string" },
      note: { type: "string" },
    },
  },
  Pagination: {
    type: "object",
    properties: {
      page: { type: "integer" },
      limit: { type: "integer" },
      total: { type: "integer" },
      pages: { type: "integer" },
    },
  },
  Role: {
    type: "string",
    enum: ["USER", "ADMIN"],
  },
  SectionType: {
    type: "string",
    enum: [
      "META",
      "GENERAL",
      "COVER",
      "HOME",
      "COUNTDOWN",
      "BRIDE",
      "EVENT",
      "INSTAGRAM",
      "PRAYER",
      "FOOTER",
      "GALLERY",
      "MUSIC",
      "ENVELOPE",
      "GIFT",
      "LIVE",
      "STORY",
      "RUNDOWN",
      "GUEST_BOOK",
      "RSVP",
      "THEME",
      "ADDITIONAL_INFO",
    ],
  },
} as const;
